controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_reports:
    path: /reports
    controller: App\Controller\ReportsController::index
    methods: GET

api_reports_chart_data:
    path: /api/reports/chart-data
    controller: App\Controller\ReportsController::getChartData
    methods: GET